import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/core/layout/Navbar";
import Footer from "@/components/core/layout/Footer";



export const metadata: Metadata = {
  title: "Integrion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
